import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import { polyfillNode } from "esbuild-plugin-polyfill-node";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const polyfillPlugin = polyfillNode({
	globals: false,
	polyfills: {
		stream: true,
	},
});

// Plugin to resolve @mastra/core subpaths
const mastraResolvePlugin = {
	name: 'mastra-resolve',
	setup(build) {
		build.onResolve({ filter: /^@mastra\/core\// }, args => {
			try {
				// Use Node's resolution to find the module
				const resolved = require.resolve(args.path);
				// Convert .cjs to .js for ESM compatibility
				const jsPath = resolved.replace(/\.cjs$/, '.js');
				if (fs.existsSync(jsPath)) {
					return { path: jsPath };
				}
				return { path: resolved };
			} catch (e) {
				console.error(`Failed to resolve ${args.path}:`, e.message);
				return undefined;
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"@huggingface/transformers",
		...builtins],
	format: "cjs",
	platform: "browser",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	logOverride: {
		'require-resolve-not-external': 'silent',
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	plugins: [
		mastraResolvePlugin,
		inlineWorkerPlugin({
			plugins: [polyfillPlugin],
		}),
	],
});

// Copy plugin files to vaults
function copyToVaults() {
	const vaults = [
		path.join(process.env.HOME, "Documents/test-note/.obsidian/plugins/obsidian-llmsider"),
		path.join(process.env.HOME, "Documents/my-note/.obsidian/plugins/obsidian-llmsider"),
	];
	
	const filesToCopy = [
		{ name: "main.js", source: path.join(__dirname, "main.js") },
		{ name: "manifest.json", source: path.join(__dirname, "manifest.json") },
		{ name: "styles.css", source: path.join(__dirname, "styles.css") },
	];
	
	vaults.forEach((vaultPath) => {
		try {
			// Create directory if it doesn't exist
			if (!fs.existsSync(vaultPath)) {
				fs.mkdirSync(vaultPath, { recursive: true });
			}
			
			// Copy files
			filesToCopy.forEach(({ name, source }) => {
				if (fs.existsSync(source)) {
					fs.copyFileSync(source, path.join(vaultPath, name));
					console.log(`✓ Copied ${name} to ${vaultPath}`);
				}
			});
			
			console.log(`✓ Plugin files copied to ${vaultPath} successfully`);
		} catch (error) {
			// Ignore errors as requested
			console.log(`ℹ Could not copy to ${vaultPath} (this is non-critical):`, error.message);
		}
	});
}

if (prod) {
	await context.rebuild();
	copyToVaults();
	process.exit(0);
} else {
	await context.watch();
}
