import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import { polyfillNode } from "esbuild-plugin-polyfill-node";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
(function() {
  var _browserShims = {
    "fs": { readFileSync: function() { return ""; }, writeFileSync: function() {}, existsSync: function() { return false; }, mkdirSync: function() {}, readdirSync: function() { return []; }, promises: { readFile: function() { return Promise.resolve(""); }, writeFile: function() { return Promise.resolve(); } } },
    "path": { join: function() { return [].slice.call(arguments).join("/"); }, resolve: function() { return [].slice.call(arguments).join("/"); }, dirname: function(p) { return p ? p.replace(/\\/[^\\/]*$/, "") : "."; }, basename: function(p) { return p ? p.replace(/^.*[\\/\\/]/, "") : ""; }, extname: function(p) { var i = p ? p.lastIndexOf(".") : -1; return i > 0 ? p.slice(i) : ""; }, sep: "/", posix: {} },
    "url": { fileURLToPath: function(u) { return u; }, pathToFileURL: function(p) { return "file://" + p; }, URL: typeof URL !== "undefined" ? URL : function() {} },
    "module": { createRequire: function() { return function() { return {}; }; } },
    "crypto": { getRandomValues: typeof crypto !== "undefined" && crypto.getRandomValues ? crypto.getRandomValues.bind(crypto) : function() {} },
    "perf_hooks": { performance: typeof performance !== "undefined" ? performance : {} },
    "os": { cpus: function() { return []; }, platform: function() { return "browser"; }, homedir: function() { return "/"; } },
    "worker_threads": { isMainThread: true, parentPort: null }
  };
  if (typeof module !== "undefined" && module.require) {
    var _origRequire = module.require.bind(module);
    module.require = function shimmedRequire(id) {
      if (_browserShims[id]) return _browserShims[id];
      return _origRequire(id);
    };
  }
  if (typeof globalThis.createRequire === "undefined") {
    globalThis.createRequire = function(url) {
      return function mockRequire(id) {
        if (_browserShims[id]) return _browserShims[id];
        return {};
      };
    };
  }
})();
`;

const prod = (process.argv[2] === "production");

const polyfillPlugin = polyfillNode({
	globals: false,
	polyfills: {
		stream: true,
	},
});

// Plugin to resolve @mastra/core subpaths
const mastraResolvePlugin = {
	name: 'mastra-resolve',
	setup(build) {
		build.onResolve({ filter: /^@mastra\/core\// }, args => {
			try {
				// Use Node's resolution to find the module
				const resolved = require.resolve(args.path);
				// Convert .cjs to .js for ESM compatibility
				const jsPath = resolved.replace(/\.cjs$/, '.js');
				if (fs.existsSync(jsPath)) {
					return { path: jsPath };
				}
				return { path: resolved };
			} catch (e) {
				console.error(`Failed to resolve ${args.path}:`, e.message);
				return undefined;
			}
		});
	},
};

// Plugin to shim Node.js builtins for @mlc-ai/web-llm (browser-only package)
// WebLLM's tvmjs tries to require("fs") etc. for Node.js code paths,
// but in Obsidian's Electron renderer we need it to use fetch() instead.
const webllmNodeShimPlugin = {
	name: 'webllm-node-shim',
	setup(build) {
		// List of Node.js builtins that webllm may try to import
		const shimmedModules = ['fs', 'path', 'url', 'module', 'crypto', 'perf_hooks', 'os', 'worker_threads'];

		// Only intercept requires from within @mlc-ai packages
		for (const mod of shimmedModules) {
			build.onResolve({ filter: new RegExp(`^${mod}$`) }, args => {
				// Check if the importer is from @mlc-ai/web-llm
				if (args.importer && args.importer.includes('@mlc-ai')) {
					return { path: mod, namespace: 'webllm-node-shim' };
				}
				// Let other importers use the real module (external)
				return undefined;
			});
		}

		// Provide empty shim content for intercepted modules
		build.onLoad({ filter: /.*/, namespace: 'webllm-node-shim' }, args => {
			const shims = {
				fs: `export default {}; export const readFileSync = undefined; export const writeFileSync = undefined; export const existsSync = () => false; export const mkdirSync = undefined; export const readdirSync = () => [];`,
				path: `export default {}; export const join = (...args) => args.join('/'); export const resolve = (...args) => args.join('/'); export const dirname = (p) => p; export const basename = (p) => p; export const extname = () => '';`,
				url: `export default {}; export const fileURLToPath = (u) => u; export const pathToFileURL = (p) => p;`,
				module: `export default {}; export const createRequire = () => () => ({});`,
				crypto: `export default {};`,
				perf_hooks: `export const performance = globalThis.performance || {}; export default { performance };`,
				os: `export default {}; export const cpus = () => []; export const platform = () => 'browser';`,
				worker_threads: `export default {}; export const isMainThread = true; export const parentPort = null;`,
			};
			return {
				contents: shims[args.path] || 'export default {};',
				loader: 'js',
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"@huggingface/transformers",
		...builtins],
	format: "cjs",
	platform: "browser",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	logOverride: {
		'require-resolve-not-external': 'silent',
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	plugins: [
		webllmNodeShimPlugin,
		mastraResolvePlugin,
		inlineWorkerPlugin({
			plugins: [polyfillPlugin],
		}),
	],
});

// Copy plugin files to vaults
function copyToVaults() {
	const vaults = [
		path.join(process.env.HOME, "Documents/test-note/.obsidian/plugins/obsidian-llmsider"),
		path.join(process.env.HOME, "Documents/my-note/.obsidian/plugins/obsidian-llmsider"),
	];

	const filesToCopy = [
		{ name: "main.js", source: path.join(__dirname, "main.js") },
		{ name: "manifest.json", source: path.join(__dirname, "manifest.json") },
		{ name: "styles.css", source: path.join(__dirname, "styles.css") },
	];

	vaults.forEach((vaultPath) => {
		try {
			// Create directory if it doesn't exist
			if (!fs.existsSync(vaultPath)) {
				fs.mkdirSync(vaultPath, { recursive: true });
			}

			// Copy files
			filesToCopy.forEach(({ name, source }) => {
				if (fs.existsSync(source)) {
					fs.copyFileSync(source, path.join(vaultPath, name));
					console.log(`✓ Copied ${name} to ${vaultPath}`);
				}
			});

			console.log(`✓ Plugin files copied to ${vaultPath} successfully`);
		} catch (error) {
			// Ignore errors as requested
			console.log(`ℹ Could not copy to ${vaultPath} (this is non-critical):`, error.message);
		}
	});
}

if (prod) {
	await context.rebuild();
	copyToVaults();
	process.exit(0);
} else {
	await context.watch();
}
