import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import { polyfillNode } from "esbuild-plugin-polyfill-node";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const polyfillPlugin = polyfillNode({
	globals: false,
	polyfills: {
		stream: true,
	},
});

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"@huggingface/transformers",
		...builtins],
	format: "cjs",
	platform: "browser",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	logOverride: {
		'require-resolve-not-external': 'silent',
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	plugins: [
		inlineWorkerPlugin({
			plugins: [polyfillPlugin],
		}),
	],
});

// Copy plugin files to test vault
function copyToTestVault() {
	try {
		const testVaultPath = path.join(process.env.HOME, "Documents/test-note/.obsidian/plugins/obsidian-llmsider");
		
		// Create directory if it doesn't exist
		if (!fs.existsSync(testVaultPath)) {
			fs.mkdirSync(testVaultPath, { recursive: true });
		}
		
		// Copy main.js
		const mainJs = path.join(__dirname, "main.js");
		if (fs.existsSync(mainJs)) {
			fs.copyFileSync(mainJs, path.join(testVaultPath, "main.js"));
			console.log("✓ Copied main.js to test vault");
		}
		
		// Copy manifest.json
		const manifest = path.join(__dirname, "manifest.json");
		if (fs.existsSync(manifest)) {
			fs.copyFileSync(manifest, path.join(testVaultPath, "manifest.json"));
			console.log("✓ Copied manifest.json to test vault");
		}
		
		// Copy styles.css
		const styles = path.join(__dirname, "styles.css");
		if (fs.existsSync(styles)) {
			fs.copyFileSync(styles, path.join(testVaultPath, "styles.css"));
			console.log("✓ Copied styles.css to test vault");
		}
		
		console.log("✓ Plugin files copied to test vault successfully");
	} catch (error) {
		// Ignore errors as requested
		console.log("ℹ Could not copy to test vault (this is non-critical):", error.message);
	}
}

if (prod) {
	await context.rebuild();
	copyToTestVault();
	process.exit(0);
} else {
	await context.watch();
}